# ===================================================================
# Application
# ===================================================================
spring.application.name=servicename
server.port=8080
spring.profiles.active=dev

# ===================================================================
# Jackson
# ===================================================================
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=com.fasterxml.jackson.databind.util.StdDateFormat
spring.jackson.deserialization.fail-on-unknown-properties=false

# ===================================================================
# Actuator
# ===================================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# ===================================================================
# JPA
# ===================================================================
spring.jpa.open-in-view=false
